# Generated by Django 3.1.1 on 2020-09-28 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseManagement', '0002_auto_20200927_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='dateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
